### ISSUE TITLE
docker have no 'mkdir' permission?

### ISSUE THREAD

**Issue by yuriufo** [ucsb-seclab/packware#4]
When I run any `./exp_*.sh`:
```bash
....
[Errno 13] Permission denied: '../../results/paper'
...
```
and I type:
```bash
/packware/code/experiments $ mkdir ../../results/paper
mkdir: can't create directory '../../results/paper': Permission denied
/packware/code/experiments $
```

**Comment by 9yte** [comment]
On my end, I don't face such a problem. Have you searched over the internet what might be the issue?

**Comment by yuriufo** [comment]
> 
> 
> On my end, I don't face such a problem. Have you searched over the internet what might be the issue?

It's a problem with my local results directory permissions, sorry.
