### ISSUE TITLE
Missing file: extract_features.py 

### ISSUE THREAD

**Issue by salijona** [ucsb-seclab/packware#5]
When I run the adversarial experiment the script fails because the dependent file extract_features.py is missing. 
If you could please add that file, I would be grateful.

**Comment by itanfeng** [comment]
Yes, I have met the same problem. The file extract_features.py is missing. Could you provide it?

**Comment by 9yte** [comment]
Just uploaded the scripts. Sorry that I have missed your comment for a very long time...
